# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line:   1

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Code with the wind'
tagline:          'Personal blog'
description:      'Where time goes while solving programming challenges'
url:              https://nejcskofic.github.io
baseurl:          ''

author:
  name:           'Nejc Skofic'
  url:            https://nejcskofic.github.io/about

paginate:         5

sass:
  style:          compressed

# Custom vars
social:
  linkedin_user:  nejc-%25C5%25A1kofi%25C4%258D-525932120
  github_user:    nejcskofic
  stackoverflow_user: 8401618/nejcs

defaults:
  -
    scope:
      path:       ""
      type:       "posts"
    values:
      layout:     "post"
      comments:   true
