# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Code with the wind'
tagline:          'Personal blog'
description:      'Time flies when you are having fun'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

excerpt_separator: <!--more-->

# Custom vars

