# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Code with the wind'
tagline:          'Personal blog'
description:      'Time flies when you are having fun'
url:              https://nejcskofic.github.io/
baseurl:          /

author:
  name:           'Nejc Skofic'

paginate:         5

excerpt_separator: <!--more-->

sass:
  style:          compressed

# Custom vars
social:
  linkedin_user:  nejc-%25C5%25A1kofi%25C4%258D-525932120
  github_user:    nejcskofic
